training:
  # 训练基本参数
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
  early_stopping_patience: 10
  
  # 优化器配置
  optimizer:
    name: "adam"
    params:
      weight_decay: 0.0001
      beta1: 0.9
      beta2: 0.999

  # 学习率调度器
  scheduler:
    name: "reduce_on_plateau"
    params:
      mode: "min"
      factor: 0.1
      patience: 5
      min_lr: 0.00001

  # 损失函数配置
  loss:
    name: "binary_cross_entropy"
    params:
      reduction: "mean"

  # 评估指标
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "auc_roc"

  # 检查点保存配置
  checkpointing:
    save_best: true
    save_last: true
    save_frequency: 5  # 每5个epoch保存一次 