environment:
  name: "development"
  
  # 日志配置
  logging:
    level: "DEBUG"
    save_path: "experiments/logs"
    console_output: true
    
  # 数据配置
  data:
    use_sample: true  # 使用采样数据进行开发
    sample_size: 1000
    
  # 训练配置
  training:
    device: "cpu"  # 开发环境使用CPU
    num_workers: 2
    pin_memory: false
    
  # 调试配置
  debug:
    enabled: true
    verbose: true
    profile: true 