environment:
  name: "production"
  
  # 日志配置
  logging:
    level: "WARNING"
    save_path: "/var/log/attendance_predict"
    console_output: false
    file_rotation: true
    max_file_size: 100  # MB
    backup_count: 10
    
  # 数据配置
  data:
    use_sample: false
    batch_processing: true
    batch_size: 1000
    
  # 训练配置
  training:
    device: "cuda"
    num_workers: 8
    pin_memory: true
    
  # 生产环境特定配置
  production:
    model_serving:
      host: "0.0.0.0"
      port: 8000
      workers: 4
      timeout: 30
    monitoring:
      enable_prometheus: true
      metrics_port: 9090
    security:
      enable_authentication: true
      enable_ssl: true
      ssl_cert_path: "/etc/ssl/certs/attendance.crt"
      ssl_key_path: "/etc/ssl/private/attendance.key" 