environment:
  name: "testing"
  
  # 日志配置
  logging:
    level: "INFO"
    save_path: "experiments/logs"
    console_output: true
    
  # 数据配置
  data:
    use_sample: false  # 使用完整测试数据集
    validation_size: 0.2
    
  # 训练配置
  training:
    device: "cuda"  # 测试环境使用GPU
    num_workers: 4
    pin_memory: true
    
  # 测试配置
  testing:
    save_predictions: true
    metrics_output_path: "outputs/metrics"
    prediction_output_path: "outputs/predictions"
    
  # 调试配置
  debug:
    enabled: false
    verbose: false
    profile: false 